version: '3.0'
services:
  postgres: 
    container_name: bd_messanger
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
